- hosts: haproxy
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
    - name: install haproxy
      apt:
        name: haproxy
        state: present
    - name: Enable in config
      replace:
        dest: '/etc/default/haproxy'
        regexp: 'ENABLED=0'
        replace: 'ENABLED=1'
    - name: Update HAProxy with config
      template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        backup: yes
      notify:
        - restart haproxy
  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted